<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">formatPerusahaan</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly9waXBlbGluZQ0KSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJz
b3IoKTsNCglTdHJpbmcgbmFtYVBlcnVzYWhhYW4gPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKHBpcGVs
aW5lQ3Vyc29yLCAibmFtYVBlcnVzYWhhYW4iKTsNCglTdHJpbmcgc3RhdHVzUGVydXNhaGFhbiA9
IElEYXRhVXRpbC5nZXRTdHJpbmcocGlwZWxpbmVDdXJzb3IsICJzdGF0dXNQZXJ1c2FoYWFuIik7
DQpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7DQoNCi8vIHByb2Nlc3MNCmlmIChuYW1hUGVydXNh
aGFhbi5zdGFydHNXaXRoKCJQVC4iKSAmJiAiVGVyYnVrYSIuZXF1YWxzKHN0YXR1c1BlcnVzYWhh
YW4pKSB7DQpuYW1hUGVydXNhaGFhbiA9IG5hbWFQZXJ1c2FoYWFuLnRvVXBwZXJDYXNlKCkuY29u
Y2F0KCIgVGJrLiIpOw0KfQ0KDQovL3BpcGVsaW5lDQpJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNv
cl8xID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQpJRGF0YVV0aWwucHV0KHBpcGVsaW5lQ3Vyc29y
XzEsICJuYW1hUGVydXNhaGFhbiIsIG5hbWFQZXJ1c2FoYWFuKTsNCnBpcGVsaW5lQ3Vyc29yXzEu
ZGVzdHJveSgpOw==</value>
</Values>
